### ISSUE TITLE
Python script doesnt match up to so

### ISSUE THREAD

**Issue by sanktanglia** [Perfare/Il2CppDumper#142]
I managed to dump out the so and meta data from in memory for a new game, after trying a few options i got the dll created, but the python script it generated doesnt appear to correspond with actual function locations in the .so

**Comment by Perfare** [comment]
dumped .so function address based on dump address, I will consider a plan to fix it.

**Comment by fantasyz** [comment]
> dumped .so function address based on dump address, I will consider a plan to fix it.
Does it mean CodeRegistration & MetadataRegistration is incorrect? Is there any way we could fix it on out side before a new update is ready? 

I am tried to dump a game appeared to be compiled with Unity 5.6.6f2 but the address seems to be incorrect. Not sure if it is because the Unity version is too old that dumper does not support it or the dumper is just broken right now. Really hope this can be working.

**Comment by Perfare** [comment]
Fixed.
