### ISSUE TITLE
Add support WebAssembly

### ISSUE THREAD

**Issue by Perfare** [Perfare/Il2CppDumper#202]
Related issue #162

**Comment by AndnixSH** [comment]
It's compiled as asm and zipped as .unityweb.
zipped .unityweb can be opened using 7zip which contains another .unityweb
global-metadata.dat can be grabbed from web.data.unityweb using hex editor but not sure how to guess the correct size of it
[web.zip](https://github.com/Perfare/Il2CppDumper/files/3994942/web.zip)

**Comment by HoLLy-HaCKeR** [comment]
I've been working on a wasm decompiler a while ago and I may make my own global-metadata reader at some point. Once I've got something that works, I'll post a link to it here. I'd submit a PR for this project but the source is an absolute mess...

**Comment by AndnixSH** [comment]
That's interesting. No popular decompiler tools can even recognise wasm
Someone wrote a module for Ghidra https://github.com/andr3colonel/ghidra_wasm
Blog https://andr3colonel.github.io/

Btw, a guy shared his own .unityweb extractor tool after I reported issue regarding .unityweb support for UABE

https://github.com/DerPopo/UABE/issues/312

[web.data.unityweb_dump.zip](https://github.com/Perfare/Il2CppDumper/files/4003171/web.data.unityweb_dump.zip)

**Comment by Brian151** [comment]
@HoLLy-HaCKeR 

exactly how viable is WASM decompilation? i know a pure disassembly SHOULD go off well, short of the devs using obfuscation/encryption, because web assembly is still fairly high-level and you can't have what happens in say, x86, where data/code get intermingled and attempts to decompile result in garbage code and data which is actually code, etc... [and guessing exactly where/what locals/params are since they can be in the stack, or the heap, or be on the heap with a pointer on the stack. if you're really lucky, REGISTERS]

but, WASM technically doesn't need the names table and does behave more like a native CPU. so say you had a function that does something to an image structure/object, and the module doesn't have its names table, wouldn't that cause a LOT of problems? 

or is it ALSO possible to aide this process using the type tree, similar to how UABE already can display the raw data of any asset/component in a file because the type tree describes the format of these objects?

**Comment by HoLLy-HaCKeR** [comment]
You can try my decompiler for yourself [here](https://github.com/holly-hacker/wasmlib). It basically converts the wasm to basic pseudo-c without applying any transformations to it, auto-generating names for functions that are not im/exported. In the future I'll look into how the metadata.dat file works and integrate that to produce output with more names. I also have to do some work to convert wasm's block-based control flow to a proper control flow graph to get better C-like control flow structs (eg. switch cases). I haven't worked on it for a while now since I'm working on other projects too.

**Comment by Brian151** [comment]
i'll have to take a look at that later
i can relate to having...multiple projects...XD

**Comment by Perfare** [comment]
Recently, I started to research WebAssembly, and have completed most of the content of WebAssembly. Now I just need to think about how to automatically search the pointer.

**Comment by Perfare** [comment]
The auto search part has been completed temporarily. But some of the problems, such as the range of bss needed for searching, is the value of the STATICTOP variable initialized in js. It may be possible to directly specify a very large value, but I have not tested more examples. Or maybe consider another search method. But for the time being, I will not continue to research WebAssembly.
