### ISSUE TITLE
Metadata can't be dumped

### ISSUE THREAD

**Issue by thienha1** [Perfare/Il2CppDumper#21]
How to solve that?
https://i.imgur.com/XAvKvpQ.jpg

**Comment by Perfare** [comment]
It looks like Metadata has been encrypted, You should decrypt the data by yourself.

**Comment by evildog1** [comment]
What game is it? I like to look at game security

**Comment by thienha1** [comment]
Honkai Impact 3rd TW

**Comment by evildog1** [comment]
Can you link to playstore or other sites?

**Comment by thienha1** [comment]
Here: https://m.apkpure.com/%E5%B4%A9%E5%A3%8A3rd/com.miHoYo.bh3tw

**Comment by evildog1** [comment]
The metadata header similar to this were removed to prevent dumping. I identified the metadata version as 22
`AF 1B B1 FA  16 00 00 00  00 01 00 00  38 59 01 00`

The is currently no way to recover the file because this bytes `38 59 01 00` is genereated for each games and putting it on other games does not work. Hope someone can explain what that bytes means
