### ISSUE TITLE
增加对retdec插件在cutter的导出脚本支持

### ISSUE THREAD

**Issue by x-tiger** [Perfare/Il2CppDumper#238]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.0.3
- 目标Unity版本
2019.2.20
- 问题描述
这玩意https://github.com/avast/retdec-r2plugin反编译出来的伪C比IDA的要好（可惜IDA的retdec插件只支持32位的ARM），然后我找到了这个开源的反编译工具https://github.com/radareorg/cutter，大佬能不能增加对这个软件和插件的支持。
- 上传可执行文件和global-metadata.dat

[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/4288938/libil2cpp.zip)
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4288944/global-metadata.zip)

**Comment by x-tiger** [comment]
大佬好快的速度，感谢支持！想问问大佬对这个cutter和retdec的看法！

**Comment by dogtopus** [comment]
I was actually going to add radare2/cutter support for Il2CppDumper and had some work done. I might actually pick it up again sometime later and get it merged since I got more il2cpp binaries to look at.

BTW are you sure you want to use retdec on il2cpp binaries? Those binaries are usually huge and retdec have serious performance issues (both execution time and memory usage)  on even slightly larger binaries.
