### ISSUE TITLE
Meta Files

### ISSUE THREAD

**Issue by firesgc** [Perfare/Il2CppDumper#352]
Hello,

Thank you for this awesome tool!

I have question regarding meta files:
Is it possible to somehow recover the meta files as well? At the moment I have a lot of missing scripts that I have to correct by hand (if I am able to find out which file is the right one)

Cheers,

**Comment by Perfare** [comment]
I did not understand what kind of Meta Files you mentioned. Are you referring to global-metadata.dat or something else?

**Comment by firesgc** [comment]
Oh, I'm sorry.

I created a new Unity project and added data from UTinyRipper to it. Then I added c# files to the project (I used IL2CPPDumper and extracted the c# files via ILSpy). But Unity is not able to make the connection between the scene data and the c# files. 

Is there a better way to deal with this problem?

Thanks a lot!

**Comment by Perfare** [comment]
First, you need to put the DummyDll folder in the game directory that needs to be exported, so that UtinyRipper can export the correct MonoBehaviour. 
In addition, I am sorry that I cannot answer the question about how to connect with the c# script, I am not a game developer, the program is only responsible for restoring dummydll either.

**Comment by firesgc** [comment]
I will try it! Thank you very much!
