### ISSUE TITLE
Header file using some reserved keywords

### ISSUE THREAD

**Issue by neobenedict** [Perfare/Il2CppDumper#360]
- Il2CppDumper version
Latest

- Target Unity version
2018.4.4

- Describe the issue
Some reserved words are being added as parameter names to the `il2cpp.h` file. These should be renamed (eg to `linux_`) when they are generated so the .h file is usable in code. Otherwise clang reports an error due to trying to use these keywords as parameters.

In FGO:
`linux`
`stdin`
`stdout`
`stderr`

- Upload executable file and global-metadata.dat
https://apkpure.com/fate-grand-order-english/com.aniplex.fategrandorder

**Comment by therealchjones** [comment]
I believe these are created by the original program and compiler and only extracted by il2cppdumper. (No, that doesn't help, but it's not that il2cppdumper is "adding" these as much as not filtering them out.) Agreed it would be worthwhile to filter out or modify reserved words, but that is a *huge* list given the compilers and languages (and decompilers, and other parsers) needing to be supported. (Running into a similar problem that was tough to track down because a variable had been named "_asm".)
