### ISSUE TITLE
Ghidra scripts do not apply known information about Parameters.

### ISSUE THREAD

**Issue by Smileynator** [Perfare/Il2CppDumper#366]
The Dummy DLL generated by this project has knowledge about parameter type, and parameter name.
These are not added to the function's settings when methods are created in Ghidra.
It is relatively trivial to add given you have access to the data. 

Returns type:
https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Function.html#setReturnType(ghidra.program.model.data.DataType,ghidra.program.model.symbol.SourceType)

Parameters type and name:
https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Function.html#replaceParameters(ghidra.program.model.listing.Function.FunctionUpdateType,boolean,ghidra.program.model.symbol.SourceType,ghidra.program.model.listing.Variable...)

Adding this functionality gives ghidra much more information to base decompilation on.

**Comment by therealchjones** [comment]
See also issue #287, specifically @tellowkrinkle's [comment and script modifications](https://github.com/Perfare/Il2CppDumper/issues/287#issuecomment-690035000)  

Will require more testing to confirm, but appropriate types have to be included first or (I think) ghidra won't change the function types. Also, currently script crashes if (I think) changes to functions have already been made manually. Working on it.

**Comment by therealchjones** [comment]
Doesn't appear to be due to previously modified functions. The script @tellowkrinkle supplied crashes if type does not already exist with Scripting Console output:
`ghidra-new.py> Running...`
`Traceback (most recent call last):`
`  File "Z:\APK\Marvel Future Fight\il2cppdumper\ghidra-new.py", line 90, in <module>`
`    set_type(addr, scriptMetadata["Signature"].encode("utf-8"))`
`  File "Z:\APK\Marvel Future Fight\il2cppdumper\ghidra-new.py", line 30, in set_type`
`    createData(addr, typeSig.getReturnType())`
`AttributeError: 'NoneType' object has no attribute 'getReturnType'`
`ghidra-new.py> Finished!`

and User Log:

> ERROR (CParserUtils) Invalid Function Signature: Function signature parse failed Encountered " <IDENTIFIER> "System_MonoType_array "" at line 1, column 1. Was expecting one of: <PRAGMA> ... "#line" ... <LINEALT> ... ";" ... System_MonoType_array* a()  

where "System_MonoType_array" (in this case) is the undefined type. Don't yet know why there's a type in script.json that's not in il2cpp.h. Looking into it.

**Comment by tellowkrinkle** [comment]
Note: There's probably a better way to convert a C type name to a Ghidra DataType object, I just find the Ghidra scripting documentation really hard to find anything in and went for the "hey it's a part of this other function" approach (I append ` a()` to it, run the function prototype parser, and then extract the return type)

**Comment by therealchjones** [comment]
What works, works. :-) Agreed the API documentation isn't straightforward, especially so for the Python/Jython stuff. It's still nice work, @tellowkrinkle. @Smileynator's links above may work, but it's going to take me some time to figure out the aforementioned issues rather than just patching on workarounds.

**Comment by therealchjones** [comment]
I'm working on the script, finding it takes forever and doesn't make the changes I want, possibly because I intentionally imported the types and ran the script prior to "auto analysis" and disassembly, so the function creation method won't make the function, so the function signature setting method won't set it.... working on fixing it, but may require further edits (or instructions to disassemble prior to running)

**Comment by therealchjones** [comment]
I've been working on this, and it's a PITA, mainly because (at this point) of ghidra errors in parsing that have been tough to track down. (Turns out a parameter name can't be _asm, for instance.) Working through these as they come up, but this may be limited somewhat by #360 . Feel free to look at [this branch](https://github.com/therealchjones/Il2CppDumper/blob/ghidra-make-params/Il2CppDumper/ghidra.py), but it's not ready for a PR yet.

**Comment by therealchjones** [comment]
Filed #378 . Please test if you can. Note that (for it to be useful) types/structs from il2cpp.h need to be imported/parsed before running the script.
