### ISSUE TITLE
how to use GameGuardian to dump?  I can't find global-metadata :/

### ISSUE THREAD

**Issue by LELEOTV** [Perfare/Il2CppDumper#383]
![perfunta](https://user-images.githubusercontent.com/73145217/96665879-41e5cc80-132c-11eb-96c3-ac92ee207219.png)

**Comment by huohuo0470** [comment]
globalmetadata is generally contained in original game apk:  assets\bin\Data\Managed\Metadata  
What you should find in gameguardian is libil2cpp.so and in picture you have found it.
xxx.BIN file can be renamed to xxx.SO file.Additionly,you should fix that xxx.BIN file so that Il2Cppdumper can identify it.

**Comment by huohuo0470** [comment]
But how to fix xxx.BIN file is a big problem, it may probably refered to a lot of knowledge,such as IDA,address find etc

**Comment by LELEOTV** [comment]
ENTENDI, NÃO EXISTE ALGUM TUTORIAL SOBRE ISSO ?

**Comment by Perfare** [comment]
Search AF 1B B1 FA in all bin files, after finding it, cut the previous part, and the rest can be loaded as global-metadata.

**Comment by lendariosregedit** [comment]
@Perfare Não vai, não funciona :-1:

**Comment by premnayek996-commits** [comment]
Hex editor open global metadata file code
