### ISSUE TITLE
Problem: il2cpp file not supported

### ISSUE THREAD

**Issue by Flury17** [Perfare/Il2CppDumper#697]
- Il2CppDumper version: Il2CppDumper-win-v6.7.38

- Target Unity version: Unity 2017.3.0f3 (64-bit)

- Describe the issue: I get this error when I put the global-metadata.dat file into your program.
   It would mean alot to me if you helped me fix this. The error is shown on the attached file.
   Apparently, you cant upload .dat files on Github so heres a mediafire link: 

https://www.mediafire.com/file/yom62wetqovf0xu/global-metadata.dat/file

![Capture4](https://user-images.githubusercontent.com/126823822/222549930-a8422973-a94d-46b7-83c6-2119c2f191ad.PNG)

**Comment by IroniaTheMaster** [comment]
both the original file and the dump give the same error..., I used Il2cppInspector as an example to show the specific error, both programs give the same error. The file is not protected, just the strings are messed up because the Devs must have done this. The error is the one I sent. I noticed that the global-metadata.dat file takes longer to load compared to il2cpp.so. You can see here one of the screenshots I tried in the il2cppInspector GUI program

![image](https://user-images.githubusercontent.com/70151358/222575996-c2ecfed1-7f94-4b70-98c9-3ddb9c665f88.png)




![image](https://user-images.githubusercontent.com/70151358/222576456-869eff99-13e8-471e-9a33-7621d503073b.png)
original il2cpp.so file without dump


![image](https://user-images.githubusercontent.com/70151358/222576574-dbce1bb6-f5ac-4e3a-b795-de0fb4b1714e.png)

**Comment by Flury17** [comment]
Why did you close this?? I dont remember giving me an answer.
